// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJtu97wJo7RVBq-AAAYOF33zvCj5RclU',
    appId: '1:962290849811:web:7f60b00ee9419aa44947e6',
    messagingSenderId: '962290849811',
    projectId: 'strate-x',
    authDomain: 'strate-x.firebaseapp.com',
    storageBucket: 'strate-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcALoLa3N0s2fg8nUw6Ai_YaG5hSa1BK0',
    appId: '1:962290849811:android:6a1cef7dbdfee78d4947e6',
    messagingSenderId: '962290849811',
    projectId: 'strate-x',
    storageBucket: 'strate-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxptIKa3kPIpStIeIbFgFyzldDBiPTvzc',
    appId: '1:962290849811:ios:22b4a18a653960064947e6',
    messagingSenderId: '962290849811',
    projectId: 'strate-x',
    storageBucket: 'strate-x.appspot.com',
    iosClientId: '962290849811-f8vlpm96kroli34jc9kds71t3mhu8gk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.str8texFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxptIKa3kPIpStIeIbFgFyzldDBiPTvzc',
    appId: '1:962290849811:ios:22b4a18a653960064947e6',
    messagingSenderId: '962290849811',
    projectId: 'strate-x',
    storageBucket: 'strate-x.appspot.com',
    iosClientId: '962290849811-f8vlpm96kroli34jc9kds71t3mhu8gk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.str8texFrontend',
  );
}
